services:

  postgres:
    container_name: postgresLibrary
    image: postgres:13.3
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - library

  backend:
    build:
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://postgresLibrary:5432/library
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      LIBRARY_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - library

networks:
  library:
    driver: bridge