services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - library

  backend:
    build:
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/library
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - library

networks:
  library:
    driver: bridge